"""empty message

Revision ID: 0691f3ae5746
Revises: 91e952c5818c
Create Date: 2023-05-09 18:24:57.707634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0691f3ae5746'
down_revision = '91e952c5818c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.alter_column('instrument',
               existing_type=sa.VARCHAR(),
               type_=sa.UUID(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.alter_column('instrument',
               existing_type=sa.UUID(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
