"""empty message

Revision ID: 06bab92d22d5
Revises: 5a34433fccd7
Create Date: 2023-05-09 18:44:59.003869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06bab92d22d5'
down_revision = '5a34433fccd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_form',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('work_start_time', sa.Time(), nullable=True),
    sa.Column('work_end_time', sa.Time(), nullable=True),
    sa.Column('instrument', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher_form')
    # ### end Alembic commands ###
