"""empty message

Revision ID: 5a34433fccd7
Revises: 8ab5829723a6
Create Date: 2023-05-09 18:42:32.960728

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5a34433fccd7'
down_revision = '8ab5829723a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_form',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('prefer_start_time', sa.Time(), nullable=True),
    sa.Column('prefer_end_time', sa.Time(), nullable=True),
    sa.Column('instrument', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('records')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('records',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('prefer_start_time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('prefer_end_time', postgresql.TIME(), autoincrement=False, nullable=True),
    sa.Column('instrument', sa.UUID(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='records_pkey')
    )
    op.drop_table('student_form')
    # ### end Alembic commands ###
