"""empty message

Revision ID: 5f4fe337fa77
Revises: 4ea04dd7ca41
Create Date: 2023-05-15 21:27:15.825125

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f4fe337fa77'
down_revision = '4ea04dd7ca41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result_schedule_form', schema=None) as batch_op:
        batch_op.add_column(sa.Column('day', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('result_schedule_form', schema=None) as batch_op:
        batch_op.drop_column('day')

    # ### end Alembic commands ###
