"""empty message

Revision ID: 88acc09dddcf
Revises: 0691f3ae5746
Create Date: 2023-05-09 18:33:59.190525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88acc09dddcf'
down_revision = '0691f3ae5746'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instruments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('instrument', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('prefer_start_time', sa.DateTime(), nullable=True),
    sa.Column('prefer_end_time', sa.DateTime(), nullable=True),
    sa.Column('instrument', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('records')
    op.drop_table('instruments')
    # ### end Alembic commands ###
