"""empty message

Revision ID: e15d2d6328e6
Revises: 4eb8194fd408
Create Date: 2023-05-09 17:49:54.432245

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e15d2d6328e6'
down_revision = '4eb8194fd408'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('prefer_start_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('prefer_end_time', sa.DateTime(), nullable=True))
        batch_op.drop_column('start_time')
        batch_op.drop_column('end_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('prefer_end_time')
        batch_op.drop_column('prefer_start_time')

    # ### end Alembic commands ###
