"""empty message

Revision ID: e1f57922b989
Revises: 06bab92d22d5
Create Date: 2023-05-09 18:59:41.260923

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1f57922b989'
down_revision = '06bab92d22d5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('result_schedule_form',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('student', sa.UUID(), nullable=True),
    sa.Column('teacher', sa.UUID(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('instrument', sa.UUID(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('result_schedule_form')
    # ### end Alembic commands ###
