"""empty message

Revision ID: ff4a7c28ea10
Revises: 5f4fe337fa77
Create Date: 2023-05-17 18:46:58.126753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff4a7c28ea10'
down_revision = '5f4fe337fa77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('teacher_form',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('work_start_time', sa.Time(), nullable=True),
    sa.Column('work_end_time', sa.Time(), nullable=True),
    sa.Column('instrument', sa.ARRAY(sa.UUID()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('teacher_form')
    # ### end Alembic commands ###
